const lightMode = {
  color: {
    disable: "#6d6d6d",
    primary: "#264653",
    secondary: "#3d3d3d",
    tertiary1: "#f4a261",
    tertiary2: "#e76f51",
    tertiary3: "#e9c46a",
    colorsNeutralHigh: "#4f4f4f",
    colorsNeutralHigher: "#3d3d3d",
    colorsNeutralHighest: "#262626",
    colorsNeutralLow: "#b0b0b0",
    colorsNeutralLower: "#e7e7e7",
    colorsNeutralLowest: "#f6f6f6",
    colorsNeutralMedium: "#6d6d6d",
    colorsSurfaceHigh: "#6d6d6d",
    colorsSurfaceHigher: "#4f4f4f",
    colorsSurfaceHighest: "#3d3d3d",
    colorsSurfaceLow: "#e7e7e7",
    colorsSurfaceLower: "#f6f6f6",
    colorsSurfaceLowest: "#ffffff",
    colorsSurfaceMedium: "#b0b0b0",
    colorsSurfaceOpposite: "#262626",
    colorsTextDisable: "#b0b0b0",
    colorsTextOpposite: "#ffffff",
    colorsTextPrimary: "#262626",
    colorsTextSecondary: "#3d3d3d",
    colorsTextTerciary: "#6d6d6d",
  },
};
const darkMode = {
  color: {
    disable: "#6d6d6d",
    primary: "#c8ff2f",
    secondary: "#000000",
    tertiary1: "#f4a261",
    tertiary2: "#e76f51",
    tertiary3: "#e9c46a",
    colorsNeutralHigh: "#6d6d6d",
    colorsNeutralHigher: "#b0b0b0",
    colorsNeutralHighest: "#f6f6f6",
    colorsNeutralLow: "#4f4f4f",
    colorsNeutralLower: "#3d3d3d",
    colorsNeutralLowest: "#262626",
    colorsNeutralMedium: "#6d6d6d",
    colorsSurfaceHigh: "#575757",
    colorsSurfaceHigher: "#888888",
    colorsSurfaceHighest: "#e7e7e7",
    colorsSurfaceLow: "#3d3d3d",
    colorsSurfaceLower: "#262626",
    colorsSurfaceLowest: "#000000",
    colorsSurfaceMedium: "#454545",
    colorsSurfaceOpposite: "#ffffff",
    colorsTextDisable: "#6d6d6d",
    colorsTextOpposite: "#262626",
    colorsTextPrimary: "#ffffff",
    colorsTextSecondary: "#d1d1d1",
    colorsTextTerciary: "#b0b0b0",
  },
};
const brand1 = {
  number: {
    fontSizeXs: "12px",
    fontSizeSm: "14px",
    fontSizeMd: "16px",
    fontSizeLg: "20px",
    fontSizeXl: "24px",
    fontSize2xl: "32px",
    fontSize3xl: "40px",
    fontSize4xl: "72px",
  },
  string: {
    fontFamilyTagline: "Inter",
    fontFamilyText: "Inter",
    fontFamilyTitle: "Inter",
    fontWeightBold: "bold",
    fontWeightExtraBold: "extrabold",
    fontWeightItalic: "italic",
    fontWeightMedium: "medium",
    fontWeightRegular: "regular",
    fontWeightSemiBold: "semibold",
  },
};
const brand2 = {
  number: {
    fontSizeXs: "12px",
    fontSizeSm: "14px",
    fontSizeMd: "16px",
    fontSizeLg: "20px",
    fontSizeXl: "24px",
    fontSize2xl: "32px",
    fontSize3xl: "40px",
    fontSize4xl: "72px",
  },
  string: {
    fontFamilyTagline: "Montserrat",
    fontFamilyText: "ubuntu",
    fontFamilyTitle: "ubuntu",
    fontWeightBold: "bold",
    fontWeightExtraBold: "extrabold",
    fontWeightItalic: "italic",
    fontWeightMedium: "medium",
    fontWeightRegular: "regular",
    fontWeightSemiBold: "semibold",
  },
};
